### ISSUE TITLE
Generic HTTPError in push_to_datastore

### ISSUE THREAD

**Issue by tedstrauss** [ckan/datapusher#132]
I'm getting the same error as reported in #69, which is now closed. Re-opening here :(
I get it with any kind of data file I try to add using the datapusher: csv, image, txt, bin.

Datapusher error log:
```
[Wed Apr 05 16:36:30.350499 2017] [:info] [pid 826] mod_wsgi (pid=826): Create interpreter 'ckan:8800|'.
[Wed Apr 05 16:36:30.352388 2017] [:info] [pid 826] [remote 127.0.0.1:28364] mod_wsgi (pid=826, process='datapusher', application='ckan:8800|'): Loading WSGI script '/etc/ckan/datapusher.wsgi'.
[Wed Apr 05 16:36:36.536371 2017] [:error] [pid 826] Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
[Wed Apr 05 16:36:36.536416 2017] [:error] [pid 826] Traceback (most recent call last):
[Wed Apr 05 16:36:36.536426 2017] [:error] [pid 826]   File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
[Wed Apr 05 16:36:36.536434 2017] [:error] [pid 826]     retval = job.func(*job.args, **job.kwargs)
[Wed Apr 05 16:36:36.536442 2017] [:error] [pid 826]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 330, in push_to_datastore
[Wed Apr 05 16:36:36.536449 2017] [:error] [pid 826]     resource = get_resource(resource_id, ckan_url, api_key)
[Wed Apr 05 16:36:36.536457 2017] [:error] [pid 826]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 278, in get_resource
[Wed Apr 05 16:36:36.536484 2017] [:error] [pid 826]     check_response(r, url, 'CKAN')
[Wed Apr 05 16:36:36.536492 2017] [:error] [pid 826]   File "/usr/lib/ckan/datapusher/src/datapusher/datapusher/jobs.py", line 153, in check_response
[Wed Apr 05 16:36:36.536499 2017] [:error] [pid 826]     request_url=request_url, response=response.text)
[Wed Apr 05 16:36:36.536506 2017] [:error] [pid 826] HTTPError: Not found status=404 url=https://myckansite.ca/api/3/action/resource_show response={"help": "https://myckansite.ca/api/3/action/help_show?name=resource_show", "success": false, "error": {"message": "Not found", "__type": "Not Found Error"}}
```

**Comment by tedstrauss** [comment]
I was able to resolve this problem eventually by adjusting the SSL settings in the NGINX conf.

**Comment by tedstrauss** [comment]
CC: https://github.com/ckan/datapusher/issues/116
