### ISSUE TITLE
error push_to_datastore Only "http, https, and ftp resources may be fetched."

### ISSUE THREAD

**Issue by lbegines** [ckan/datapusher#164]
I have the following error when I try to push data to the datastore.

I´m working in a development enviromental with ckan 2.7.0. Can anyone help me with this?

Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/datapusher/datapusher/jobs.py", line 342, in push_to_datastore
    'Only http, https, and ftp resources may be fetched.'
JobError

Can anyone help me with this?

**Comment by Chealer** [comment]
What is the URL of the resource you are trying to push?
