### ISSUE TITLE
Datapusher: 500 Server Error

### ISSUE THREAD

**Issue by Thekings2468** [ckan/datapusher#166]
Hello, so it's my first time using CKAN and I followed the CKAN doc (package installation) to install it on a VPS over SSH (Ubuntu 14.04 LTS). I did all the steps but when I was to use datapusher in the CKAN site it gave me an error 
`Upload error: An Error occurred while sending the job: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8800/job`
I search for a solution but I can't find anyone with the same problem as mine.
Another thing is that `curl 0.0.0.0:8800` gives me this error aswell (500 Internal Error in html).

Stacktrace: 
```
[Fri May 11 17:00:44.668900 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704] mod_wsgi (pid=25904): Target WSGI script '/etc/c$
[Fri May 11 17:00:44.669061 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704] mod_wsgi (pid=25904): Exception occurred process$
[Fri May 11 17:00:44.669204 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704] Traceback (most recent call last):
[Fri May 11 17:00:44.669283 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704]   File "/etc/ckan/datapusher.wsgi", line 8, in <$
[Fri May 11 17:00:44.669416 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704]     import ckanserviceprovider.web as web
[Fri May 11 17:00:44.669439 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704]   File "/usr/lib/ckan/datapusher/lib/python2.7/s$
[Fri May 11 17:00:44.669491 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704]     import flask.ext.login as flogin
[Fri May 11 17:00:44.669632 2018] [:error] [pid 25904:tid 139861721458432] [remote 127.0.0.1:28704] ImportError: No module named ext.login
```
I have followed the steps [here](https://github.com/ckan/datapusher/issues/165) as the error is the same, but it didn't work (even by restarting apache2 and nginx).

**Comment by krzpam** [comment]
Thekings2468, how did you solve this problem?

**Comment by francescoVenuto** [comment]
@Thekings2468, @krzpam,

Hi, I'm Francesco Venuto, I work for Corvallis SPA at Caltagirone, Italy. 
During one of the many installations of CKAN I had the same problem.
**The error:**
_________________________________________________________________________________________
Target WSGI script '/etc/ckan/datapusher.wsgi' can not be loaded as Python module.
Exception occurred processing WSGI script '/etc/ckan/datapusher.wsgi'.
Traceback (most recent call last):
 File "/etc/ckan/datapusher.wsgi", line 8, in <module>
 import ckanserviceprovider.web as web
 File "/usr/lib/ckan/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.py", line 13, in <mod $
 import flask.ext.login as flogin
 ImportError: No module named ext.login
_________________________________________________________________________________________

You have to check if the modules Flask and Flask_login are installed and if necessary install them:

_pip uninstall flask_   (if is installed in other version)
_pip install flask == 0.12_

_pip install flask-login_

then you have to check the file /ckanserviceprovider/web.py  (possible path):
 _/usr/lib/ckan/datapusher/lib/python2.7/site-packages/ckanserviceprovider/web.py_

and replace: _import flask.ext.login as flogin_

with: _import flask_login as flogin_

because flask.ext.login is obsolete

finally restart datastore and ckan

_sudo a2ensite datapusher
sudo service apache2 restart_

I hope you have been helpful
Greetings and best wishes

Francesco Venuto

**Comment by krzpam** [comment]
It works! Thank you :)

**Comment by Thekings2468** [comment]
I got through the steps @francescoVenuto suggested while googling, but you have to enter datapusher's own virtualenv and execute the pip commands for it to work.

**Comment by JudyMor** [comment]
Hi I running CKAN 2.8.2 and flask 0.12.4 and am getting the same error.  Any ideas of what else could cause the issue.

**Comment by davidread** [comment]
@judymor have you considered switching to ckanext-xloader? datapusher is not being maintained afaict.

**Comment by JudyMor** [comment]
Hi David,

Thanks for your reply.

I have another question.

I normally start httpd  to start ckan.


BUT when I use . /usr/lib/ckan/default/bin/activate for the virtual env can you tell me if there are any PIDs I can detect to see if virtual environment is active.



I have done a ps –ef but cannot identify any processes that have ckan (ps –ef | grep ckan) in them



Judy.

**Comment by JudyMor** [comment]
Hi David thanks for the reply.

The Linux administrators have downloaded ckanext-xloader.

It has ended up in /usr/lib/python2.7/site-packages.

drwxr-xr-x.  3 root root    21 May 28 13:11 ckanext
-rw-r--r--.  1 root root   544 May 28 13:11 ckanext_xloader-0.3.1-py2.7-nspkg.pth
drwxr-xr-x.  2 root root   171 May 28 13:11 ckanext_xloader-0.3.1-py2.7.egg-info


I believe it should have been in directory /usr/local/ckan/lib/default/src/ckan/ckanext where all the other extensions are.
I
s it ok to copy into this directory??  Hopefully no back end files were updated at the same TIME???


usr/local/ckan/lib/default/src/ckan/ckanext/example_theme_docs/v21_custom_jquery_plugin/fanstatic/example_theme_popover.min.js
/usr/local/ckan/lib/default/src/ckan/ckanext/example_theme_docs/v21_custom_jquery_plugin/fanstatic/jquery.greenify.js
/usr/local/ckan/lib/default/src/ckan/ckanext/example_theme_docs/v21_custom_jquery_plugin/fanstatic/jquery.greenify.min.js
/usr/local/ckan/lib/default/src/ckan/ckanext/example_theme_docs/v21_custom_jquery_plugin/templates/ajax_snippets
/usr/local/ckan/lib/default/src/ckan/ckanext/example_theme_docs/v21_custom_jquery_plugin/templates/snippets
/usr/local/ckan/lib/default/src/ckan/ckanext/example_theme_docs/v21_custom_jquery_plugin/templates/snippets/package_item.html
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/__init__.py
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/__init__.pyc
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/plugin.py
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/plugin.pyc
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/tests
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/theme
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/tests/__init__.py
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/tests/test_view.py
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/theme/templates
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/theme/templates/image_form.html
/usr/local/ckan/lib/default/src/ckan/ckanext/imageview/theme/templates/image_view.html
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/__init__.py
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/plugin.py
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/tests
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/dutch_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/english_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/fr_elision.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/french_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/german_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/greek_stopwords.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/italian_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/polish_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/portuguese_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/romanian_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/schema.xml
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/solr/spanish_stop.txt
/usr/local/ckan/lib/default/src/ckan/ckanext/multilingual/tests/test_multilingual_plugin.py
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/__init__.py
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/__init__.pyc
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/plugin.py
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/plugin.pyc
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/tests
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/theme
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/tests/__init__.py
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/tests/test_view.py
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/theme/public
/usr/local/ckan/lib/default/src/ckan/ckanext/reclineview/theme/templates

**Comment by MiguelGuzmanDev** [comment]
@davidread Someone has tried ckanext-xloader, if not, does it affect the views?
