### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by zaisahil** [ckan/datapusher#167]
When I run this line of code: 
`python2.7 datapusher/main.py deployment/datapusher_settings.py`

I get this error:
`root@DA-CKAN:~/datapusher# python2.7 datapusher/main.py deployment/datapusher_settings.py
Traceback (most recent call last):
  File "datapusher/main.py", line 3, in <module>
    import ckanserviceprovider.web as web
  File "/usr/local/lib/python2.7/dist-packages/ckanserviceprovider/web.py", line 13, in <module>
    import flask.ext.login as flogin
ImportError: No module named ext.login
root@DA-CKAN:~/datapusher# 
`

**Comment by nicholsn** [comment]
Duplicate of https://github.com/ckan/datapusher/issues/165
