### ISSUE TITLE
do not strip header value when type datetime.

### ISSUE THREAD

**Issue by deniszgonjanin** [ckan/datapusher#63]
A bit of an edge case, but thought I'd put it here anyway. 

When an .xls has a column header that is a properly formatted date, it is imported as datetime.datetime. Datapusher will try to strip the value, causing the below exception:

Offending file: https://dl.dropboxusercontent.com/u/6526141/cap180201.xls (second sheet in the excel file)

Trace:
```
Job "push_to_datastore (trigger: RunTriggerNow, run = True, next run at: None)" raised an exception
Traceback (most recent call last):
  File "/Users/dz/Envs/datapusher/lib/python2.7/site-packages/apscheduler/scheduler.py", line 512, in _run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/dz/source/datapusher/datapusher/jobs.py", line 346, in push_to_datastore
    headers = [header.strip() for header in headers if header.strip()]
AttributeError: 'datetime.datetime' object has no attribute 'strip'
```

**Comment by wardi** [comment]
where is this handled? can we convert all the headers to unicode in the datastore before calling strip?
