### ISSUE TITLE
Error running datapusher on RedHat 6.7

### ISSUE THREAD

**Issue by jroigfer** [ckan/datapusher#94]
I'm installing datapusher, on Apache 2.4 and mod_wsgi 4.4, from source on RedHat 6.7 and CKAN 2.4.1 ,when datapusher is called using curl to check that it was succesfull installed, it fails and returns a 500 error.

I tested with Apache 2.2 and 2.4, and mod_wsgi 4.4 and 3.5, and I was reading the Apache documentation and decided to  add  the next parameters:
WSGIScriptAlias / /etc/ckan/datapusher.wsgi
WSGIPassAuthorization On
WSGIDaemonProcess ckan display-name=ckan processes=1 threads=15
header-buffer-size=32768
WSGIProcessGroup ckan
WSGIApplicationGroup %{GLOBAL}
WSGIPythonHome /xxxxx/opendata/ckan/datapusher/
WSGIPythonPath /xxxxx/opendata/ckan/datapusher/lib64/python2.6/

Without any success, I  checked the Selinux configuration or the installed Python dependences. Testing different configurations, I discovered that if I comment the line "import datapusher.jobs as jobs" in the datapsuher.wsgi I receive a correct response from datapusher. But when the line is not commented, datapusher fails and returns the following errors:

Error log Apache 2.4:

```
[Thu Feb 04 14:41:20.990935 2016] [core:notice] [pid 35032] AH00051: child pid 35033 exit signal Segmentation fault (11), possible coredump in /xxxx/xxxxx/xxxx
[Thu Feb 04 14:41:20.991037 2016] [:info] [pid 35032] mod_wsgi (pid=35033): Process 'ckan' has died, restarting.
[Thu Feb 04 14:41:20.991048 2016] [:info] [pid 35032] mod_wsgi (pid=35033): Process 'ckan' terminated by signal 11
```

Error log Datapusher:

```
[Thu Feb 04 14:41:19.571200 2016] [:error] [pid 35033] /xxxx/opendata/ckan/datapusher/lib/python2.6/site-packages/flask_login.py:154: DeprecationWarning: Warning setup_app is deprecated. Please use init_app.
[Thu Feb 04 14:41:19.571242 2016] [:error] [pid 35033]   DeprecationWarning)
[Thu Feb 04 14:41:20.514952 2016] [core:error] [pid 35036] [client 127.0.0.1:33996] End of script output before headers: datapusher.wsgi
```

If datapusher is called directly, everything is ok, but when it is called through Apache and mod_wsgi, the errors appear. 

When I use datapsuher with the importing jobs line ("import datapusher.jobs as jobs") commented, it returns the next error in logs:

```
[Tue Feb 09 15:04:26.383416 2016] [:error] [pid 26395] Exception on /job [POST]
[Tue Feb 09 15:04:26.383446 2016] [:error] [pid 26395] Traceback (most recent call last):
[Tue Feb 09 15:04:26.383453 2016] [:error] [pid 26395]   File "/xxxx/opendata/ckan/datapusher/lib/python2.6/site-packages/flask/app.py", line 1687, in wsgi_app
[Tue Feb 09 15:04:26.383459 2016] [:error] [pid 26395]     response = self.full_dispatch_request()
[Tue Feb 09 15:04:26.383464 2016] [:error] [pid 26395]   File "/xxxx/opendata/ckan/datapusher/lib/python2.6/site-packages/flask/app.py", line 1360, in full_dispatch_request
[Tue Feb 09 15:04:26.383469 2016] [:error] [pid 26395]     rv = self.handle_user_exception(e)
[Tue Feb 09 15:04:26.383475 2016] [:error] [pid 26395]   File "/xxxx/opendata/ckan/datapusher/lib/python2.6/site-packages/flask/app.py", line 1358, in full_dispatch_request
[Tue Feb 09 15:04:26.383480 2016] [:error] [pid 26395]     rv = self.dispatch_request()
[Tue Feb 09 15:04:26.383485 2016] [:error] [pid 26395]   File "/xxxx/opendata/ckan/datapusher/lib/python2.6/site-packages/flask/app.py", line 1344, in dispatch_request
[Tue Feb 09 15:04:26.383490 2016] [:error] [pid 26395]     return self.view_functions[rule.endpoint](**req.view_args)
[Tue Feb 09 15:04:26.383495 2016] [:error] [pid 26395]   File "/xxxx/opendata/ckan/datapusher/lib/python2.6/site-packages/ckanserviceprovider/web.py", line 624, in job
[Tue Feb 09 15:04:26.383501 2016] [:error] [pid 26395]     ).format(job_type, ', '.join(job_types))
[Tue Feb 09 15:04:26.383505 2016] [:error] [pid 26395] ValueError: zero length field name in format.
```

**Comment by jroigfer** [comment]
Solved using Python
